version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
  #      - echo Logging in to Amazon ECR...
  #      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
     - mvn compile
      - docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.1.4-20220427
#      - docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:4.1.4-20220427
#      - docker run -d -p 4445:4444 -p 7901:7900 --shm-size="2g" selenium/standalone-edge:4.1.4-20220427
#      - docker run -d -p 4446:4444 -p 7902:7900 --shm-size="2g" selenium/standalone-firefox:4.1.4-20220427
      #      - echo Build started on `date`
      #      - echo Building the Docker image.......
     
  post_build:
    commands:
#    - echo Build completed on `date`
#      - echo Pushing the Docker image...
